captracker/urls.py
from django.urls import path

from . import views

app_name = 'captracker'
urlpatterns = [
    path('', views.captracker, name='captracker'),
    path('trade/view/<tid>', views.view_trade, name='viewTrade'),
    path('trade/add', views.add_trade, name='addTrade'),
    path('trade/submitTrade', views.submit, name='submit'),

]

liga/urls.py
from django.urls import path

from . import views

app_name = 'liga'
urlpatterns = [
    path('', views.index, name='index'),
    path('rosters/<int:owner_id>', views.rosters, name='rosters'),
    path('rosters/<int:owner_id>/update/', views.update, name='update'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('', include('liga.urls')),
    url(r'^franchise/', include('franchise.urls')),
    url(r'^captracker/', include('captracker.urls')),
    url(r'^admin/', admin.site.urls),
]

captracker/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse

from liga.models import Owner
from liga.models import Trade
from liga.models import Player
from liga.models import Roster


##########
# #              Render Cap Tracker Page
##########
def captracker(request):
    owner_list = Owner.objects.all()
    trades = Trade.objects.all()
    cap_movements = Trade.objects.filter(cap__isnull=False)
    cap_exchange = []

    for trade in cap_movements:
        curr = parse_cap_trade(trade.tradeID, trade.recipient, trade.giver, trade.cap)
        cap_exchange.append(curr)

    context = {
        'owner_list': owner_list,
        'trades': trades,
        'cap_exchange': cap_exchange,
    }
    return render(request, 'captracker/captracker.html', context)


##########
# #              Render View Trade Page
##########
def view_trade(request, tid):
    owner_list = Owner.objects.all()
    trades = Trade.objects.filter(tradeID=tid)
    full_trade = parse_full_trade(trades)

    parse_full_trade(trades)
    context = {
        'owner_list': owner_list,
        'tid': tid,
        'trade': full_trade,
    }
    return render(request, 'captracker/viewTrade.html', context)


##########
# #              Render Add Trade Page
##########
def add_trade(request):
    owner_list = Owner.objects.all()
    rosters_list = Roster.objects.all()
    context = {
        'owner_list': owner_list,
        'rosters_list': rosters_list,
    }
    return render(request, 'captracker/addTrade.html', context)


##########
# #
# #              Returns [tid, {'owner': <Owner>, 'cap_rec': cap_received}, {'owner': <Owner>, 'cap_rec': cap_received}]
# #
##########
def parse_cap_trade(tid, f_owner, s_owner, cap):
    f_owner = owner_recs(f_owner, cap)
    s_owner = owner_recs(s_owner, cap * -1)
    my_trade = [tid, f_owner, s_owner]
    return my_trade


##########
# #              Returns Dictionary of owner key and cap received
##########
def owner_recs(owner, cap_received):
    dict1 = {
        'owner': owner,
        'cap_rec': cap_received,
    }
    return dict1


##########
# #              Returns Array of 2 Dicts:
# #                 [{   owner: <Owner>
# #                     cap: num
# #                     players_received: [<Player1> , <Player2>, ...]
# #                 }, ...]
##########
def parse_full_trade(trade_items):
    full_trade = []
    first = 0

    # Everything first owner receives
    dict1 = {}
    p1_recs = []

    # Everything second owner receives
    dict2 = {}
    p2_recs = []

    for asset in trade_items:
        if first == 0:
            dict1['owner'] = asset.recipient
            dict2['owner'] = asset.giver
            dict1['cap_rec'] = asset.cap
            dict2['cap_rec'] = asset.cap * -1
            first += 1

        # if owner1 is recipient
        if asset.recipient == dict1['owner']:
            p1_recs.append(asset.athlete)
        else:
            p2_recs.append(asset.athlete)

    dict1['players_received'] = p1_recs
    dict2['players_received'] = p2_recs
    full_trade.append(dict1)
    full_trade.append(dict2)
    return full_trade


##########
#                FORM: Add Trade
#                Process the form for adding a trade
##########

def submit(request):
    trade = Trade.objects.all().order_by('-tradeID')
    new_trade_id = trade[0].tradeID + 1

    # Cap the first player receives
    fcap = get_int(request, 'o1_cap')

    # boolean if owner2 receives cap (or no cap)
    second = fcap == 0
    owner2 = Owner.objects.get(pk=request.POST.get('owner2'))
    owner1 = Owner.objects.get(pk=request.POST.get('owner1'))

    # Create dict of players received { key: id }
    players_to_o1 = {k: v for (k, v) in request.POST.items() if 'o1_p' in k}
    players_to_o2 = {k: v for (k, v) in request.POST.items() if 'o2_p' in k}

    # Reformat to Array of Players
    try:
        if len(players_to_o1) + len(players_to_o2) == 0:
            raise ObjectDoesNotExist('Must have a player')
        o1_players = []
        for (k, v) in players_to_o1.items():
            o1_players.append(Player.objects.get(pk=v))

        o2_players = []
        for (k, v) in players_to_o2.items():
            o2_players.append(Player.objects.get(pk=v))

        if len(o1_players) != len(set(o1_players)) or len(o2_players) != len(set(o2_players)):
            raise ObjectDoesNotExist('Duplicate player error')
        cap_rec = fcap

    except ObjectDoesNotExist:
        owner_list = Owner.objects.all()
        rosters_list = Roster.objects.all()
        context = {
            'owner_list': owner_list,
            'rosters_list': rosters_list,
            'error_message': "Invalid Player Selection"
        }
        return render(request, 'captracker/addTrade.html', context)

    # If owner 2 receives cap
    if second:
        cap_rec = get_int(request, 'o2_cap')
        if len(o2_players) == 0:
            # owner 1 gets
            create_trade_elements(new_trade_id, owner1, owner2, o1_players, cap_rec * -1, True)
        else:
            # owner 2 gets
            create_trade_elements(new_trade_id, owner2, owner1, o2_players, cap_rec, True)
            # owner 1 gets
            create_trade_elements(new_trade_id, owner1, owner2, o1_players, 0, False)
    else:
        if len(o1_players) == 0:
            # owner 2 gets
            create_trade_elements(new_trade_id, owner2, owner1, o2_players, cap_rec * -1, True)
        else:
            # owner 1 gets
            create_trade_elements(new_trade_id, owner1, owner2, o1_players, cap_rec, True)
            # owner 2 gets
            create_trade_elements(new_trade_id, owner2, owner1, o2_players, 0, False)

    return HttpResponseRedirect(reverse('captracker:captracker'))


##########
#                Returns string as int
##########
def get_int(request, which):
    num = request.POST.get(which)
    if num == '':
        my_num = 0
    else:
        my_num = int(num)
    return my_num


##########
#                Creates and saves a single entry in Trade table
##########
def create_trade_elements(tid, rec, giv, player_list, cap, include_cap):
    for player in player_list:
        # update the trade
        t = Trade(tradeID=tid, recipient=rec, giver=giv, athlete=player)
        if include_cap:
            t.cap = cap
            include_cap = False
            rec.cap += cap
            giv.cap -= cap
            rec.save()
            giv.save()
        t.save()

        # update the rosters
        r = Roster.objects.get(athlete=player)
        r.owner = rec
        r.save()

captracker/templates/captracker/addTrade.html
<!--
    Template for Adding a New Trade Page
-->

{% extends "./trade_base.html" %}

{% block Title %} Add Trade{% endblock Title %}

{% block error_message %}
{% if error_message %}
<div class="error_message"> {{ error_message }}</div>
{% endif %}
{% endblock error_message %}

{% block form_content %}

<div>

    <form action="{% url 'captracker:submit' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <!-- Owner 1 -->
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                <div>
                    Owner 1:
                    <select class='ownersel' id="owner1" name="owner1">
                        <option value=-99 name="none"> Select an Owner</option>
                        {% for owner in owner_list %}
                        <option value={{owner.pk}} name={{owner.name}} class="owner1_rec_player"> {{owner.name}}
                        </option>
                        {% endfor %}
                    </select> <br>
                </div>

                <div id="players_div1">
                    <!-- Dynamically Populated Player Select Fields -->
                </div>
                <br>
                <button type="button" class="btn btn-default btn-sm" onclick="addPlayer('o1_p', 'players_div1')">
                    <span class="glyphicon glyphicon-plus"></span> Add Player
                </button>

            </div>

            <div class="col-xs-1 col-sm-2 col-md-2 col-lg-2"></div>
            <!-- Owner 2 -->

            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                <div>
                    Owner 2:
                    <select class='ownersel' id="owner2" name="owner2">
                        <option value=-99 name="none"> Select an Owner</option>
                        {% for owner in owner_list %}
                        <option value={{owner.pk}}> {{owner.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div id="players_div2">
                    <!-- Dynamically Populated Player Select Fields -->
                </div>
                <br>
                <button type="button" class="btn btn-default btn-sm" onclick="addPlayer('o2_p', 'players_div2')">
                    <span class="glyphicon glyphicon-plus"></span> Add Player
                </button>
            </div>
        </div>

        <br>
        <!--    Cap     -->
        <div class="row">
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                <span id="cap1">Cap: <input type="number" name="o1_cap" id="caprec1"> </span>
            </div>
            <div class="col-xs-1 col-sm-2 col-md-2 col-lg-2">
                <center><span class="glyphicon glyphicon-arrow-right" id="switchCap"></span></center>
            </div>
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                <span id="cap2" style="display:none">Cap: <input type="number" name="o2_cap" id="caprec2"> </span>
            </div>

        </div>
        <br>
        <center><input class="mybtn" style="display:none" id="submit_form" type="submit" value="Submit"></center>
    </form>
</div>
{% endblock form_content %}

{% block owner1 %}<span id="fowner">Owner 1</span> {% endblock owner1 %}
{% block owner2 %} <span id="sowner">Owner 2</span> {% endblock owner2 %}


{% block scripts %}
<script>

$(document).ready(function(){

    // Click on swap button, moves cap form element to opposite owner
    $("span#switchCap").click(function(){
            capSwap();
            $("#cap1").toggle();
            $("#cap2").toggle();
            $("span#switchCap").toggleClass("glyphicon-arrow-right");
            $("span#switchCap").toggleClass("glyphicon-arrow-left");
    })

});

    // Changing owner 1 - filtering list of owner2, filtering players owner2 can receive
    $('#owner1').on('change', function(){
        filterList("owner1", "owner2");
        filterPlayers($('#owner1').val(), "players_div2");
        $("span#fowner").text($('#owner1 option:selected').text());
        showSubmit();
    });

    // Changing owner 2 - filtering list of owner1, filtering players owner1 can receive
    $('#owner2').on('change', function(){
        filterList("owner2", "owner1");
        filterPlayers($('#owner2').val(), "players_div1");
        $("span#sowner").text($('#owner2 option:selected').text());
        showSubmit();
    });

    // Filter list of owners based on other owner selected
    function filterList(o1, o2) {
        $("#" + o2 + " > option").each(function() {
             $(this).show();
             if( $('#' + o1).val() == $(this).val()){
                $(this).hide();
             }
        });
    }

    // Filter list of players depending on other owner selected
    function filterPlayers(ownerid, which){
        $('#' + which + ' select option').each(function() {
             $(this).show();
             if($(this).attr('class') != ownerid.toString()){
                 $(this).hide();

             }
        });
    }

    // Transfer value typed from one to the other one
    function capSwap(){
        var temp = 0;
        if($("#caprec1").is(":hidden")) {
            temp = $("#caprec2").val();
            $("#caprec1").val(temp);
            $("#caprec2").val(0)
        }
        else{
            temp = $("#caprec1").val();
            $("#caprec2").val(temp);
            $("#caprec1").val(0)
        }
    }

    // local variable to count field ids
    var player = 1

    // Dynamically create and populate a select form element
    function addPlayer(who, which) {

        //Create and append select list
        var selectPlayerList = document.createElement("select");
        selectPlayerList.id = who + player;
        selectPlayerList.name = who + player;

        var outerdiv = "<div id=" + player + "> </div"
        $("#" + which).append(outerdiv);

        var txt1 = "<span> <br> Player: ";
        var txt2 = "<button type='button' class='btn btn-default btn-sm' onclick='remove_div(" + player + ")' > <span class='glyphicon glyphicon-trash'></span> </button> </span>"
        $("div#" + player).append(txt1, selectPlayerList, txt2);

        populate_option(selectPlayerList, -99, "none", "Select a Player");

        //Populate with all players
        {% for roster in rosters_list %}
           var val = {{roster.athlete.pk}};
           var name = "{{roster.athlete.name}}";
           var txt = "{{roster.athlete.name}}";
           oid = "{{roster.owner.pk}}";
           populate_option(selectPlayerList, val, name, txt, oid);
        {% endfor %}

        if (who == 'o1_p'){
            owner = 'owner2';
        }
        else{
            owner = 'owner1';
        }
        filterPlayers($('#' + owner).val(), which);
        player++;
    }


    // Remove div containing "player: [Select] (trash)"
    function remove_div(id){
        console.log(id);
        $("div#" + id).remove();
    }

    // Append Player to select
    function populate_option(list, val, nme, txt, oid){
        var option = document.createElement("option");
        option.value = val;
        option.id = player + "-" + val;
        option.name = nme;
        option.text = txt;

        list.appendChild(option);
        if(oid){
            $("option#" + player + "-" + val).addClass(oid);
        }
    }

    // Decide if form is valid to display submit button
    function showSubmit(){
         if($('#owner1').val() < 0 || $('#owner2').val() < 0){
            $('#submit_form').hide();
         }
         else{
            $('#submit_form').show();
         }
    }






</script>
{% endblock scripts %}

captracker/templates/captracker/captracker.html
<!--
    Template for Cap Tracker/View all Trades Page
-->

{% extends "liga/base.html" %}
{% block Title %} Cap Tracker {% endblock Title %}


{% block main_content %}
<div class="container table-responsive">

    <table class="table .table-sm table-hover">
        <thead>
        <tr>
            <th scope="col"></th>
            {% for owner in owner_list %}
            <th scope="col">{{owner.name}}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <!-- Cap -->
        <tr>
            <td><b>Cap Space</b></td>
            {% for owner in owner_list %}
            <td> {{owner.cap}}</td>
            {% endfor %}
        </tr>
        <!-- Trades -->
        {% for trade in cap_exchange %}
        <tr>
            <td><a href="{% url 'captracker:viewTrade' trade.0 %}"> Trade {{trade.0}} </a></td>
            {% for owner in owner_list %}
            <td>
                {% if trade.1.owner == owner %}
                {{ trade.1.cap_rec }}
                {% elif trade.2.owner == owner %}
                {{ trade.2.cap_rec }}
                {% endif %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}

        </tbody>
    </table>


</div>
<center><a href="{% url 'captracker:addTrade' %}" class="btn btn-info btn-lg mybtn">
    <span class="glyphicon glyphicon-plus"></span> Add Trade
</a></center>

{% endblock main_content %}

captracker/templates/captracker/trade_base.html
<!--
    Base template for displaying a trade
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block Title %}{% endblock Title %}</title>

    {% include "liga/jquery_include.html" %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'liga/style.css' %}">

</head>

<body>
{% include "liga/navbar.html" %}

{% block error_message %}{% endblock error_message %}
<div class="container"> <!-- If Needed Left and Right Padding in 'md' and 'lg' screen means use container class -->
    <!--    Back to Cap Tracker -->

    <a href="{% url 'captracker:captracker' %}" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-arrow-left"></span> Back to Cap Tracker
    </a>

    <div class="row">
        <!-- Owner 1 Receives -->
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
            <table class="table .table-sm">
                <thead>
                <tr>
                    <th scope="col">{% block owner1 %} {% endblock owner1 %} Receives</th>
                </tr>
                </thead>
                <tbody>
                {% block table1_body %} {% endblock table1_body %}
                </tbody>
            </table>
        </div>

        <div class="col-xs-1 col-sm-2 col-md-2 col-lg-2"></div>

        <!-- Owner 2 Receives -->
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
            <table class="table .table-sm">
                <thead>
                <tr>
                    <th scope="col"> {% block owner2 %} {% endblock owner2 %} Receives</th>
                </tr>
                </thead>
                <tbody>
                {% block table2_body %} {% endblock table2_body %}
                </tbody>
            </table>
        </div>
        </tbody>
        </table>
    </div>
    {% block form_content %} {% endblock form_content %}
</div>

{% block scripts %} {% endblock scripts %}
</body>
</html>
</html>

captracker/templates/captracker/viewTrade.html
<!--
    Template for View Trade Details Page
-->

{% extends "./trade_base.html" %}

{% block Title %} View Trade{% endblock Title %}

{% block owner1 %} {{trade.0.owner}} {% endblock owner1 %}

{% block table1_body %}
<!-- Cap -->
<tr>
    {%if trade.0.cap_rec > 0 %}
    <td>$ {{trade.0.cap_rec}}</td>
    {% endif %}
</tr>

<!-- Players -->
{%for i in trade.0.players_received %}
<tr>
    <td>{{ i.name }}</td>
</tr>
{% endfor %}
{% endblock table1_body %}

{% block owner2 %} {{trade.1.owner}} {% endblock owner2 %}


{% block table2_body %}
<!-- Cap -->
<tr>
    {%if trade.1.cap_rec > 0 %}
    <td> $ {{trade.1.cap_rec}}</td>
    {% endif %}
</tr>
<!-- Players -->
{%for i in trade.1.players_received %}
<tr>
    <td>{{ i.name }}</td>
</tr>
{% endfor %}
{% endblock table2_body %}