franchise/urls.py
from django.urls import path

from . import views

app_name = 'franchise'
urlpatterns = [
    path('', views.franchise, name='index'),
    path('update/<str:position>', views.update, name='update'),
]

liga/urls.py
from django.urls import path

from . import views

app_name = 'liga'
urlpatterns = [
    path('', views.index, name='index'),
    path('rosters/<int:owner_id>', views.rosters, name='rosters'),
    path('rosters/<int:owner_id>/update/', views.update, name='update'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('', include('liga.urls')),
    url(r'^franchise/', include('franchise.urls')),
    url(r'^captracker/', include('captracker.urls')),
    url(r'^admin/', admin.site.urls),
]

franchise/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from liga.models import Player
from django.urls import reverse
from liga.functions import update_franchise_tag, keeper_update


##########
#                Render Franchise Tag Page
##########
def franchise(request):
    qb_list = get_list("QB")
    rb_list = get_list("RB")
    wr_list = get_list("WR")
    te_list = get_list("TE")
    tag_prices = []
    for i in range(4):
        tag_prices.append(Player.objects.filter(name__contains='Franchise').values('price')[i]['price'])
    context = {
        'qb_list': qb_list,
        'rb_list': rb_list,
        'wr_list': wr_list,
        'te_list': te_list,
        'tag_prices': tag_prices,
    }
    return render(request, 'franchise/franchise.html', context)


##########
#                FORM: Update the Franchise Tag Price
##########
def update(request, position):
    list = get_list(position)
    kept_list = request.POST.getlist('item')

    for player in list:
        player.kept = False
        player.save()

    keeper_update(kept_list)
    update_franchise_tag(position)
    return HttpResponseRedirect(reverse('franchise:index'))


##########
#                Returns queryset of players filtered by specific position
##########
def get_list(position):
    if position == "QB" or position == "TE":
        return Player.objects.filter(position=position).exclude(name__contains='Franchise').order_by('-price')
    else:
        return Player.objects.filter(position=position).exclude(name__contains='Franchise').filter(
            price__gte=19).order_by('-price')

franchise/templates/franchise/franchise.html
<!--
    Template for View Franchise Tags Page
-->

{% extends "liga/base.html" %}
{% block Title %} Franchise {% endblock Title %}


{% block main_content %}


<div class="container-fluid">
    <div class="row">

        <!--    Quarterback Section -->
        <form action="{% url 'franchise:update' 'QB' %}" method="post">
            {% csrf_token %}
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <h3>
                    <center> Quarterback
                        <br> Franchise tag: ${{tag_prices.0}}
                    </center>
                </h3>

                <center><input class="mybtn" type="submit" value="Recalculate"></center>
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">Player</th>
                        <th scope="col">Price</th>
                        <th scope="col">Keep?</th>
                    </tr>
                    </thead>
                    <!-- Each player's information -->
                    <tbody>
                    {% for qb in qb_list %}
                    <tr>
                        <td> {{qb.name}}</td>
                        <td> {{qb.price}}</td>
                        <td><input type="checkbox" name="item" id="qb{{ forloop.counter }}" value="{{ qb.id }}"
                                   {% if qb.kept %} checked {% endif %}>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <!--    Running Back Section -->
        <form action="{% url 'franchise:update' 'RB' %}" method="post">
            {% csrf_token %}

            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <h3>
                    <center> Running Back
                        <br> Franchise tag: ${{tag_prices.1}}
                    </center>
                </h3>
                <center><input class="mybtn" type="submit" value="Recalculate"></center>
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">Player</th>
                        <th scope="col">Price</th>
                        <th scope="col">Keep?</th>
                    </tr>
                    </thead>
                    <!-- Each player's information -->
                    <tbody>
                    {% for rb in rb_list %}
                    <tr>
                        <td> {{rb.name}}</td>
                        <td> {{rb.price}}</td>
                        <td><input type="checkbox" name="item" id="rb{{ forloop.counter }}" value="{{ rb.id }}"
                                   {% if rb.kept %} checked {% endif %}>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </form>


        <!--    Wide Receiver Section -->
        <form action="{% url 'franchise:update' 'WR' %}" method="post">
            {% csrf_token %}

            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <h3>
                    <center> Wide Receiver
                        <br> Franchise tag: ${{tag_prices.2}}
                    </center>
                </h3>

                <center><input class="mybtn" type="submit" value="Recalculate"></center>
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">Player</th>
                        <th scope="col">Price</th>
                        <th scope="col">Keep?</th>
                    </tr>
                    </thead>
                    <!-- Each player's information -->
                    <tbody>
                    {% for wr in wr_list %}
                    <tr>
                        <td> {{wr.name}}</td>
                        <td> {{wr.price}}</td>
                        <td><input type="checkbox" name="item" id="wr{{ forloop.counter }}" value="{{ wr.id }}"
                                   {% if wr.kept %} checked {% endif %}>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>


        <!--    Tight End Section -->
        <form action="{% url 'franchise:update' 'TE' %}" method="post">
            {% csrf_token %}
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <h3>
                    <center> Tight End
                        <br> Franchise tag: ${{tag_prices.3}}
                    </center>
                </h3>
                <center><input class="mybtn" type="submit" value="Recalculate"></center>
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">Player</th>
                        <th scope="col">Price</th>
                        <th scope="col">Keep?</th>
                    </tr>
                    </thead>
                    <!-- Each player's information -->
                    <tbody>
                    {% for te in te_list %}
                    <tr>
                        <td> {{te.name}}</td>
                        <td> {{te.price}}</td>
                        <td><input type="checkbox" name="item" id="te{{ forloop.counter }}" value="{{ te.id }}"
                                   {% if te.kept %} checked {% endif %}>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </form>
        <br>
    </div>
</div>

{% endblock main_content %}