captracker/urls.py
from django.urls import path

from . import views

app_name = 'captracker'
urlpatterns = [
    path('', views.captracker, name='captracker'),
    path('trade/view/<tid>', views.view_trade, name='viewTrade'),
    path('trade/add', views.add_trade, name='addTrade'),
    path('trade/submitTrade', views.submit, name='submit'),

]

franchise/urls.py
from django.urls import path

from . import views

app_name = 'franchise'
urlpatterns = [
    path('', views.franchise, name='index'),
    path('update/<str:position>', views.update, name='update'),
]

liga/urls.py
from django.urls import path

from . import views

app_name = 'liga'
urlpatterns = [
    path('', views.index, name='index'),
    path('rosters/<int:owner_id>', views.rosters, name='rosters'),
    path('rosters/<int:owner_id>/update/', views.update, name='update'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('', include('liga.urls')),
    url(r'^franchise/', include('franchise.urls')),
    url(r'^captracker/', include('captracker.urls')),
    url(r'^admin/', admin.site.urls),
]

liga/models.py
from django.db import models


class Owner(models.Model):
    name = models.CharField(max_length=20)
    cap = models.IntegerField()

    def __str__(self):
        return self.name


class Player(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField()
    position = models.CharField(max_length=3)
    kept = models.BooleanField()
    ftag = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Roster(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    athlete = models.ForeignKey(Player, on_delete=models.CASCADE)

    def __str__(self):
        return self.owner.name + ": " + self.athlete.name


class Trade(models.Model):
    tradeID = models.IntegerField()
    recipient = models.ForeignKey(Owner, on_delete=models.CASCADE)
    giver = models.ForeignKey(Owner, on_delete=models.CASCADE, related_name="givers")
    athlete = models.ForeignKey(Player, on_delete=models.CASCADE)
    cap = models.IntegerField(blank=True, null= True)

    def __str__(self):
        return "Trade " + str(self.tradeID) + ": " + self.giver.name + " gives " + self.athlete.name + " and $" + str(self.cap) + " to " + self.recipient.name

liga/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .models import Owner
from .models import Player
from .models import Roster
from django.urls import reverse
from .functions import update_all_tags, keeper_update


def index(request):
    context = {}
    return render(request, 'liga/index.html', context)


##########
#                Render Rosters Page
##########
def rosters(request, owner_id):
    roster_items = Roster.objects.all()

    ownership = Roster.objects.filter(owner__pk=owner_id)
    owner_name = Owner.objects.filter(pk=owner_id).values('name')[0]['name']
    max_cap = Owner.objects.filter(pk=owner_id).values('cap')[0]['cap']
    rem_cap = remaining(owner_name, max_cap)

    context = {
        'roster_items': roster_items,
        'ownership': ownership,
        'max_cap': max_cap,
        'owner_name': owner_name,
        'owner_id': owner_id,
        'rem_cap': rem_cap,
    }
    return render(request, 'liga/rosters.html', context)


##########
#                Returns the owner's remaining cap based on max cap and kept players
##########
def remaining(name, max):
    temp = Roster.objects.filter(owner__name=name).filter(athlete__kept=True)
    sum = 0
    for item in temp:
        # Account for Franchise Tag
        if item.athlete.ftag:
            pos = item.athlete.position
            tag_price_player = Player.objects.get(name__exact=pos + " Franchise")
            sum = sum + tag_price_player.price
        else:
            sum = sum + item.athlete.price
    return max - sum


##########
#                FORM: Updates the player's kept attribute
##########
def update(request, owner_id):
    owner = Owner.objects.get(pk=owner_id)
    player_id_list = request.POST.getlist('item')
    ftagged = request.POST.get('franchise')
    not_kept = Roster.objects.filter(owner_id=owner.id)

    # Defaults all to false
    for each_player in not_kept:
        each_player.athlete.kept = False
        each_player.athlete.ftag = False
        each_player.athlete.save()

    # Change checked to True
    keeper_update(player_id_list)

    # Manage franchise tag
    if ftagged:
        tagged_player = Player.objects.get(pk=ftagged)
        tagged_player.ftag = True
        tagged_player.kept = True
        tagged_player.save()

    update_all_tags()
    return HttpResponseRedirect(reverse('liga:rosters', args=(owner.id,)))

liga/templates/liga/base.html
<!--
    This is the base code that other templates reuse
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}{% endblock Title %}</title>

    {% include "liga/jquery_include.html" %}

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'liga/style.css' %}">
</head>

<body>
{% include "liga/navbar.html" %}


{% block main_content %} {% endblock main_content %}

{% block scripts %} {% endblock scripts %}
</body>
</html>

liga/templates/liga/index.html
{% extends "./base.html" %}
{% block Title %} Home Page {% endblock Title %}


{% block main_content %}

<div class="container">
    My Home Page... maybe one day I'll make a home page
</div>

{% endblock main_content %}

liga/templates/liga/jquery_include.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

liga/templates/liga/navbar.html
<nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">La Liga Fantasia Website</a>

       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
       </button>

    </div>
    <ul class="nav navbar-nav collapse navbar-collapse">
    <!-- Homepage -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'liga:index' %}">Homepage</a>
      </li>
    <!-- Rosters -->
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Rosters<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'liga:rosters' 1 %}">Kevin</a></li>
          <li><a href="{% url 'liga:rosters' 2 %}">Justin</a></li>
          <li><a href="{% url 'liga:rosters' 3 %}">Alex</a></li>
          <li><a href="{% url 'liga:rosters' 4 %}">Nikos</a></li>
          <li><a href="{% url 'liga:rosters' 5 %}">Luigi</a></li>
          <li><a href="{% url 'liga:rosters' 6 %}">Michael</a></li>
          <li><a href="{% url 'liga:rosters' 7 %}">Matt</a></li>
          <li><a href="{% url 'liga:rosters' 8 %}">Chinmay</a></li>
          <li><a href="{% url 'liga:rosters' 9 %}">Christain</a></li>
          <li><a href="{% url 'liga:rosters' 10 %}">Brent</a></li>
        </ul>
      </li>
      <!-- Franchise Tag -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'franchise:index' %}">Franchise Tag</a>
      </li>
      <!-- Cap Tracker -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'captracker:captracker' %}">Cap Tracker</a>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
      <li class="nav-item">
        <a class="nav-link" href="/admin">Admin</a>
      </li>
    </ul>
  </div>
</nav>

liga/templates/liga/rosters.html
<!--
    Template for View Roster Page
-->

{% extends "./base.html" %}
{% block Title %} {{owner_name}}'s Roster {% endblock Title %}


{% block main_content %}
<!--
    Main Table
-->
<div class="container">
    <h1> {{owner_name}} </h1>


    <center><a class="btn btn-primary" data-toggle="collapse" href="#showTeam" role="button" aria-expanded="false"
               aria-controls="showTeam">Preview Team</a></center>
    <div class="container collapse" id="showTeam">
        <!-- If Needed Left and Right Padding in 'md' and 'lg' screen means use container class -->
        <div class="row">
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">QB</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in ownership %}
                    {% if item.athlete.kept and item.athlete.position == 'QB' %}
                    <tr>
                        <td> {{item.athlete.name}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">RB</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in ownership %}
                    {% if item.athlete.kept and item.athlete.position == 'RB' %}
                    <tr>
                        <td> {{item.athlete.name}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">WR</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in ownership %}
                    {% if item.athlete.kept and item.athlete.position == 'WR' %}
                    <tr>
                        <td> {{item.athlete.name}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <table class="table .table-sm">
                    <thead>
                    <tr>
                        <th scope="col">TE</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in ownership %}
                    {% if item.athlete.kept and item.athlete.position == 'TE' %}
                    <tr>
                        <td> {{item.athlete.name}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>


        </div>

    </div>

    <form action="{% url 'liga:update' owner_id %}" method="post">
        {% csrf_token %}

        <table class="table .table-sm">
            <thead>
            <tr>
                <th scope="col">Position</th>
                <th scope="col">Player Name</th>
                <th scope="col">Price</th>
                <th scope="col">Keep?</th>
                <th scope="col">Franchise Tag</th>
            </tr>
            </thead>

            <!-- Each player's information -->
            <tbody>
            {% for item in ownership %}
            <tr>
                <td>{{item.athlete.position}}</td>
                <td> {% if item.athlete.ftag %} <b>{{item.athlete.name}} </b>
                    {% else %} {{item.athlete.name}} {% endif %}
                </td>
                <td>{{item.athlete.price}}</td>
                <td><input type="checkbox" name="item" id="item{{ forloop.counter }}" value="{{ item.athlete.id }}"
                           {% if item.athlete.kept %} checked {% endif %}>
                </td>
                <td><input type="radio" name="franchise" id="franchise{{ forloop.counter }}"
                           value="{{ item.athlete.id }}"
                           {% if item.athlete.ftag %} checked {% endif %}>
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td>No Franchise Tag</td>
                <td></td>
                <td></td>
                <td><input type="radio" name="franchise" id="franchise" value=""
                           {% if item.athlete.ftag %} checked {% endif %}></td>
            </tr>
            <tr>
                <td><b>Max Cap: </b></td>
                <td></td>
                <td>{{max_cap}}</td>
                <td></td>
                <td><input type="submit" value="Submit" class="mybtn"></td>
            </tr>
            <tr>
                <td><b>Remaining Cap: </b></td>
                <td></td>
                <td>{{rem_cap }}</td>
                <td></td>
                <td></td>
            </tr>
            </tbody>
        </table>

    </form>

</div>
{% endblock main_content %}